apiVersion: v1
kind: Service
metadata:
  name: scurity-encryption
  labels:
    app: scurity-encryption
spec:
  selector:
    app: scurity-encryption
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP