apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/member-auth
  - ../../../../../base/superapp/services/ussd-auth
  - ../../../../../base/superapp/services/member-user
  - ../../../../../base/superapp/services/fayda
  - ../../../../../base/superapp/services/migration

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa

images:
  - name: harbor.cbe.com.et/cbe-superapp/member-auth-qa
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/member-user-qa
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/ussd-auth-qa
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/fayda-qa
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/migration-qa
    newTag: latest