apiVersion: apps/v1
kind: Deployment
metadata:
  name: fayda
  labels:
    app:  fayda
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  fayda
  template:
    metadata:
      labels:
        app:  fayda
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  fayda
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/fayda-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap