apiVersion: v1
kind: Service
metadata:
  name: jenkins-hook
  labels:
    app: jenkins-hook
spec:
  selector:
    app: jenkins-hook
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP