apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-server
  labels:
    app:  pdf-server
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  pdf-server
  template:
    metadata:
      labels:
        app:  pdf-server
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  pdf-server
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/pdf-server-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap