apiVersion: v1
kind: Service
metadata:
  name: pdf-server
  labels:
    app: pdf-server
spec:
  selector:
    app: pdf-server
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP