apiVersion: apps/v1
kind: Deployment
metadata:
  name: bps-action
  labels:
    app:  bps-action
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  bps-action
  template:
    metadata:
      labels:
        app:  bps-action
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  bps-action
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/bps-action-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap