apiVersion: v1
kind: Service
metadata:
  name: bps-action
  labels:
    app: bps-action
spec:
  selector:
    app: bps-action
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP