apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget
  labels:
    app:  budget
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  budget
  template:
    metadata:
      labels:
        app:  budget
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  budget
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/budget-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap