apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/transaction
  - ../../../../../base/superapp/services/cbe-to-cbe
  - ../../../../../base/superapp/services/money-request
  - ../../../../../base/superapp/services/common


patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev
