apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/transaction
  - ../../../../../base/superapp/services/cbe-to-cbe
  - ../../../../../base/superapp/services/money-request
  - ../../../../../base/superapp/services/common


patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev


images:
  - name: harbor.cbe.com.et/cbe-superapp/transaction-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/cbe-to-cbe-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/money-request-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/common-dev
    newTag: latest