apiVersion: apps/v1
kind: Deployment
metadata:
  name: cps-auth
  labels:
    app:  cps-auth
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cps-auth
  template:
    metadata:
      labels:
        app:  cps-auth
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  cps-auth
        image: harbor.cbe.com.et/cbe-superapp/cps-auth-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap