apiVersion: v1
kind: Service
metadata:
  name: transaction
  labels:
    app: transaction
spec:
  selector:
    app: transaction
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP