apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/budget
  - ../../../../../base/superapp/services/chat
  - ../../../../../base/superapp/services/virtual-card
  - ../../../../../base/superapp/services/equb
  - ../../../../../base/superapp/services/pdf




patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa
