apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/pdf

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/pdf-server-qa
    newTag: latest