apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-uat

resources:
  - ../../../../base/superapp/services/bps-auth
  - ../../../../base/superapp/services/bps-action


patches:
  - path: patch/uat-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -uat

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/bps-auth-uat
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/bps-action-uat
    newTag: latest

