apiVersion: v1
kind: Service
metadata:
  name: virtual-card
  labels:
    app: virtual-card
spec:
  selector:
    app: virtual-card
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP