apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher
  labels:
    app:  voucher
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  voucher
  template:
    metadata:
      labels:
        app:  voucher
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  voucher
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/voucher-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap