apiVersion: v1
kind: Service
metadata:
  name: voucher
  labels:
    app: voucher
spec:
  selector:
    app: voucher
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP