apiVersion: v1
kind: Service
metadata:
  name: cbe-to-wallet
  labels:
    app: cbe-to-wallet
spec:
  selector:
    app: cbe-to-wallet
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP