apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/news
  - ../../../../../base/superapp/services/exchange-rate
  - ../../../../../base/superapp/services/chat

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa


images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/news-qa
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/exchange-rate-qa
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/chat-qa
    newTag: latest