apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
  labels:
    app:  news
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  news
  template:
    metadata:
      labels:
        app:  news
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  news
        image: harbor.cbe.com.et/cbe-superapp/news-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap