apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kafka-uat
namespace: ocpsuperapp-uat

resources:
  - ../../../base/kafka


# patches:
#   - path: patch/uat-patch.yml

nameSuffix: -uat
