apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-uat

resources:
  - ../../../../../base/superapp/services/split-payment



patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -uat

images:
  - name: harbor.cbe.com.et/cbe-superapp/split-payment-uat
    newTag: latest
