apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../base/superapp/services/cps-auth
  - ../../../../base/superapp/services/cps-action



patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev


images:
  - name: harbor.cbe.com.et/cbe-superapp/cps-auth-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/cps-action-dev
    newTag: latest