apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../base/superapp/services/cps-auth
  - ../../../../base/superapp/services/cps-action



patches:
  - path: patch/dev-patch.yml

nameSuffix: -dev
