apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../router


patches:
  - path: patch/dev-patch.yml
  - path: patch/router-patch.yml

namePrefix: bps-auth-
