apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api
  labels:
    app:  common-api
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  common-api
  template:
    metadata:
      labels:
        app:  common-api
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  common-api
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/common-api-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap