apiVersion: v1
kind: Service
metadata:
  name: common-api
  labels:
    app: common-api
spec:
  selector:
    app: common-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
    - port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP