apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-uat

resources:
  - ../../../../../base/superapp/services/equb
  - ../../../../../base/superapp/services/budget
  - ../../../../../base/superapp/services/vault

patches:
  - path: patch/uat-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -uat


images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/equb-uat
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/budget-uat
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/vault-uat
    newTag: latest