apiVersion: v1
kind: Service
metadata:
  name: ecommerce-erp
  labels:
    app: ecommerce-erp
spec:
  selector:
    app: ecommerce-erp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP