apiVersion: v1
kind: Service
metadata:
  name: donation
  labels:
    app: donation
spec:
  selector:
    app: donation
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP