apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../base/superapp/services/bps-auth
  - ../../../../base/superapp/services/bps-action


patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa
