apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/news
  - ../../../../../base/superapp/services/exchange-rate
  - ../../../../../base/superapp/services/chat

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev


images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/news-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/exchange-rate-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/chat-dev
    newTag: latest