apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/utility
  - ../../../../../base/superapp/services/utility-parser

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -staging



images:
  - name: harbor.cbe.com.et/cbe-superapp/utility-qa
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/utility-parser-qa
    newTag: latest