apiVersion: v1
kind: Service
metadata:
  name: utility
  labels:
    app: utility
spec:
  selector:
    app: utility
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP