apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../base/superapp/services/ecommerce-erp
  - ../../../../base/superapp/services/ecommerce



patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: harbor.cbe.com.et/cbe-superapp/ecommerce-erp-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/ecommerce-dev
    newTag: latest