apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/yabex

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -staging

images:
  - name: harbor.cbe.com.et/cbe-superapp/yabex-qa
    newTag: latest