apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-click-product
  labels:
    app:  three-click-product
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  three-click-product
  template:
    metadata:
      labels:
        app:  three-click-product
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  three-click-product
        image: harbor.cbe.com.et/cbe-superapp/three-click-product-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap