apiVersion: v1
kind: Service
metadata:
  name: three-click-product
  labels:
    app: three-click-product
spec:
  selector:
    app: three-click-product
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP