apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-app
  labels:
    app:  mini-app
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mini-app
  template:
    metadata:
      labels:
        app:  mini-app
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  mini-app
        image: harbor.cbe.com.et/cbe-superapp/mini-app-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap