apiVersion: v1
kind: Service
metadata:
  name: mini-app
  labels:
    app: mini-app
spec:
  selector:
    app: mini-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP