apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../base/superapp/services/bps-auth
  - ../../../../base/superapp/services/bps-action
  - ../../../../base/superapp/services/api-proxy


patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev
