apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/cbe-to-wallet
  - ../../../../../base/superapp/services/topup
  - ../../../../../base/superapp/services/donation

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: harbor.cbe.com.et/cbe-superapp/cbe-to-wallet-dev
    newTag: latest
  - name: harbor.cbe.com.et/cbe-superapp/topup-dev
    newTag: latest
