apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/file-server
  - ../../../../../base/superapp/services/pdf

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/file-server-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/pdf-server-dev
    newTag: latest