apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-uat

resources:
  - ../../../../../base/superapp/services/file-server
  - ../../../../../base/superapp/services/pdf-server

patches:
  - path: patch/uat-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -uat
