apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  labels:
    app:  file-server
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  file-server
  template:
    metadata:
      labels:
        app:  file-server
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  file-server
        image: harbor.cbe.com.et/cbe-superapp/file-server-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap