apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-payment
  labels:
    app:  split-payment
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  split-payment
  template:
    metadata:
      labels:
        app:  split-payment
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  split-payment
        image: harbor.cbe.com.et/cbe-superapp/split-payment-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap