apiVersion: v1
kind: Service
metadata:
  name: split-payment
  labels:
    app: split-payment
spec:
  selector:
    app: split-payment
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP