apiVersion: v1
kind: Service
metadata:
  name: topup
  labels:
    app: topup
spec:
  selector:
    app: topup
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
    - port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP