apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: redis-dev
namespace: ocpsuperapp-dev

resources:
  - ../../../base/redis


patches:
  - path: patchs/dev-patch.yml

nameSuffix: -dev
