apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomoca-erp-ingress
  namespace: erp-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: http01
    acme.cert-manager.io/http01-edit-in-place: "true"



spec:
  ingressClassName: nginx
  rules:
  - host: tomoca-dev.starpayethiopia.com
    http:
      paths:
      # Routes to tomoca erp service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomoca-erp
            port:
              number: 80