apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/ips


patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/ips-dev
    newTag: latest