apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/member-auth
  - ../../../../../base/superapp/services/member-user
  - ../../../../../base/superapp/services/fayda
  - ../../../../../base/superapp/services/migration
  - ../../../../../base/superapp/services/ussd-auth

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/member-auth-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/member-user-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/ussd-auth-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/fayda-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/migration-dev
    newTag: latest