apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/member-auth
  - ../../../../../base/superapp/services/member-user
  - ../../../../../base/superapp/services/fayda
  - ../../../../../base/superapp/services/migration

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev
