apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rate
  labels:
    app:  exchange-rate
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  exchange-rate
  template:
    metadata:
      labels:
        app:  exchange-rate
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  exchange-rate
        image: harbor.cbe.com.et/cbe-superapp/exchange-rate-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap