apiVersion: v1
kind: Service
metadata:
  name: exchange-rate
  labels:
    app: exchange-rate
spec:
  selector:
    app: exchange-rate
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP