apiVersion: apps/v1
kind: Deployment
metadata:
  name: standing-order
  labels:
    app:  standing-order
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  standing-order
  template:
    metadata:
      labels:
        app:  standing-order
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  standing-order
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/standing-order-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap