apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocperp-dev

resources:
  - ../../../../base/erp/services/tomoca-erp


patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: harbor.cbe.com.et/cbe-erp/tomoca-erp-dev
    newTag: latest
