apiVersion: v1
kind: Service
metadata:
  name: client-orchestrator
  labels:
    app: client-orchestrator
spec:
  selector:
    app: client-orchestrator
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP