apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../base/superapp/services/qa-utility/



patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa
