apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../../base/superapp/services/cbe-to-wallet
  - ../../../../../../base/superapp/services/topup
  - ../../../../../../base/superapp/services/utility
  - ../../../../../../base/superapp/services/cbe-a2a



patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa
