apiVersion: v1
kind: Service
metadata:
  name: member-user
  labels:
    app: member-user
spec:
  selector:
    app: member-user
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP