apiVersion: apps/v1
kind: Deployment
metadata:
  name: equb
  labels:
    app:  equb
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  equb
  template:
    metadata:
      labels:
        app:  equb
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  equb
        image: harbor.cbe.com.et/cbe-superapp/equb-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap