apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/yabex
  - ../../../../../base/superapp/services/vault
  - ../../../../../base/superapp/services/voucher
  - ../../../../../base/superapp/services/standing-order




patches:
  - path: patch/patch.yml
  - path: patch/route-patch.yml

nameSuffix: -qa
