apiVersion: v1
kind: Service
metadata:
  name: qa-utility
  labels:
    app: qa-utility
spec:
  selector:
    app: qa-utility
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP