apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-qa

resources:
  - ../../../../../base/superapp/services/virtual-card
  - ../../../../../base/superapp/services/voucher
  - ../../../../../base/superapp/services/standing-order

patches:
  - path: patch/qa-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -staging

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/virtual-card-qa
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/voucher-qa
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/standing-order-qa
    newTag: latest