apiVersion: v1
kind: Service
metadata:
  name: bps-auth
  labels:
    app: bps-auth
spec:
  selector:
    app: bps-auth
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP