apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/virtual-card
  - ../../../../../base/superapp/services/voucher
  - ../../../../../base/superapp/services/standing-order

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev

images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/virtual-card-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/voucher-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/standing-order-dev
    newTag: latest