apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: redis-uat
namespace: ocpsuperapp-uat

resources:
  - ../../../base/redis


patches:
  - path: patch/uat-patch.yml

nameSuffix: -uat
