apiVersion: apps/v1
kind: Deployment
metadata:
  name: ips
  labels:
    app:  ips
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ips
  template:
    metadata:
      labels:
        app:  ips
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  ips
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/ips-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap