apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
  labels:
    app:  api-proxy
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  api-proxy
  template:
    metadata:
      labels:
        app:  api-proxy
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  api-proxy
        image: harbor.cbe.com.et/cbe-superapp/api-proxy-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap