apiVersion: v1
kind: Service
metadata:
  name: api-proxy
  labels:
    app: api-proxy
spec:
  selector:
    app: api-proxy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP