apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ocpsuperapp-dev

resources:
  - ../../../../../base/superapp/services/equb
  - ../../../../../base/superapp/services/budget
  - ../../../../../base/superapp/services/vault

patches:
  - path: patch/dev-patch.yml
  - path: patch/route-patch.yml

nameSuffix: -dev


images:
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/equb-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/budget-dev
    newTag: latest
  - name: superapp-registry.cbe.com.et:5000/cbe-superapp/vault-dev
    newTag: latest