apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-request
  labels:
    app:  money-request
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  money-request
  template:
    metadata:
      labels:
        app:  money-request
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  money-request
        image: superapp-registry.cbe.com.et:5000/cbe-superapp/money-request-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap