apiVersion: v1
kind: Service
metadata:
  name: money-request
  labels:
    app: money-request
spec:
  selector:
    app: money-request
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP