apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbe-to-cbe
  labels:
    app:  cbe-to-cbe
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cbe-to-cbe
  template:
    metadata:
      labels:
        app:  cbe-to-cbe
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  cbe-to-cbe
        image: harbor.cbe.com.et/cbe-superapp/cbe-to-cbe-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap