apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbe-a2a
  labels:
    app:  cbe-a2a
    project: cbe-superapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cbe-a2a
  template:
    metadata:
      labels:
        app:  cbe-a2a
        project: cbe-superapp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  cbe-a2a
        image: harbor.cbe.com.et/cbe-superapp/a2a-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: superapp-env-configmap