apiVersion: v1
kind: Service
metadata:
  name: cbe-a2a
  labels:
    app: cbe-a2a
spec:
  selector:
    app: cbe-a2a
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP