apiVersion: v1
kind: Service
metadata:
  name: migration
  labels:
    app: migration
spec:
  selector:
    app: migration
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP