apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-erp
  labels:
    app:  ecommerce-erp
    project: cbe-erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ecommerce-erp
  template:
    metadata:
      labels:
        app:  ecommerce-erp
        project: cbe-erp
    spec:
      imagePullSecrets:
        - name: regcred 
      containers:
      - name:  ecommerce-erp
        image: harbor.cbe.com.et/cbe-erp/ecommerce-erp-dev:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8069
        volumeMounts:
          - mountPath: /var/lib/odoo
            name: cbe-odoo-volume
          - name: odoo-config-volume
            mountPath: /etc/odoo/odoo.conf
            subPath: odoo.conf
      volumes:
        - name: cbe-odoo-volume
          persistentVolumeClaim:
            claimName: cbe-odoo-pvc
        - name: odoo-config-volume
          configMap:
            name: odoo-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbe-odoo-pvc
  namespace: cbe-odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
