apiVersion: v1
kind: Service
metadata:
  name: tomoca-erp
  labels:
    app: tomoca-erp
spec:
  selector:
    app: tomoca-erp
  ports:
    - port: 80
      targetPort: 8069
      protocol: TCP
  type: ClusterIP