apiVersion: v1
kind: Service
metadata:
  name: utility-parser
  labels:
    app: utility-parser
spec:
  selector:
    app: utility-parser
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP